`gh-actions/github/release`: Cleanups add existing release check (#3171)
Signed-off-by: Ryan Northey <ryan@synca.io>

diff --git a/gh-actions/github/release/action.yml b/gh-actions/github/release/action.yml
--- a/gh-actions/github/release/action.yml
+++ b/gh-actions/github/release/action.yml
@@ -2,6 +2,9 @@ inputs:
   dry-run:
     type: boolean
     default: true
+  fail-if-exists:
+    type: boolean
+    default: true
   name:
     type: string
     required: true
@@ -14,21 +17,34 @@ inputs:
   template-release:
     type: string
     default: |
-      CREATE_ARGS=(\($release_args))
-      if [[ \"\(.dry_run)\" == \"true\" ]]; then
-          OUTPUT=(\"gh release create ${CREATE_ARGS[*]}\")
+      RELEASE_ARGS=(\($release_args))
+      TAG=\"\($tag)\"
+      REPO=\"\(.repo)\"
+      FAIL_IF_EXISTS=\"\(.fail_if_exists)\"
+      if gh release view \"$TAG\" --repo \"$REPO\" &>/dev/null; then
+          OUTPUT=(\"Release $TAG already exists, skipping creation\")
+          if [[ \"${FAIL_IF_EXISTS}\" == \"true\" ]]; then
+              echo \"::error::Release $TAG already exists, skipping creation\" >&2
+              exit 1
+          fi
+          echo \"::warning::Release $TAG already exists, skipping creation\" >&2
       else
-          OUTPUT=($(gh release create \"${CREATE_ARGS[@]}\"))
-      fi
-      echo \($next_version) > \(.version_file)
-      OUTPUT+=(\"git commit \(.version_file) -m \($reopen_message) --signoff\")
-      if [[ \"\(.dry_run)\" == \"true\" ]]; then
-          OUTPUT+=(\"git push origin refs/heads/main\")
-      else
-          OUTPUT+=($(git push origin refs/heads/main))
+          OUTPUT=(\"gh release create ${RELEASE_ARGS[*]}\")
+          if [[ \"\(.dry_run)\" != \"true\" ]]; then
+              OUTPUT=($(gh release create \"${RELEASE_ARGS[@]}\"))
+          fi
+          echo \($next_version) > \(.version_file)
+          OUTPUT+=(\"git commit \(.version_file) -m '\($reopen_message)' --signoff\")
+          if [[ \"\(.dry_run)\" == \"true\" ]]; then
+              OUTPUT+=(\"git push origin refs/heads/main\")
+          else
+              OUTPUT+=($(git push origin refs/heads/main))
+          fi
       fi
       OUTPUT=$(printf '%s\n' \"${OUTPUT[@]}\")
-
+  token:
+    type: string
+    required: true
   version:
     type: string
     required: true
@@ -46,10 +62,13 @@ runs:
   steps:
   - uses: envoyproxy/toolshed/gh-actions/bson@4db1102447743c6eea61debf33a67218c9d0b01a
     id: release
+    env:
+      GH_TOKEN: ${{ inputs.token }}
     with:
       input: |
         dry_run: ${{ inputs.dry-run }}
-        name: actions
+        fail_if_exists: ${{ inputs.fail-if-exists }}
+        name: ${{ inputs.name }}
         repo: ${{ inputs.repository }}
         sha: ${{ inputs.sha }}
         version: ${{ inputs.version }}
